---

rke2_config_src: .
rke2_config_dest: /etc/rancher/rke2/config.yaml
rke2_version: v1.20.11
rke2_cluster_kube_config: /etc/rancher/rke2/rke2.yaml
INSTALL_RKE2_CHANNEL: v1.20



### Helm Settings
helm_binary_version: v3.6.3
helm_binary_download_url: "https://get.helm.sh/helm-{{ helm_binary_version }}-linux-amd64.tar.gz"
helm_binary: "./helm"
helm_home: ".helm"
helm_rancher_repo: rancher-stable
helm_rancher_repo_url: "https://releases.rancher.com/server-charts/stable"
helm_rancher_version: "v2.6.0"
helm_binary_dest: /usr/local/bin/helm
# You only need to configure these "helm_certmanager_*" values if you enable
# Let's Encrypt support in the "Rancher Cluster Settings" section!
helm_certmanager_version: 1.5.1
helm_certmanager_jetstack_repo: jetstack
helm_certmanager_jetstack_repo_url: https://charts.jetstack.io

### Kubectl Settings
kubectl_binary_version: v1.21.1
kubectl_binary_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_binary_version }}/bin/linux/amd64/kubectl"
kubectl_binary: "./kubectl-{{ kubectl_binary_version }}"
kubectl_binary_dest: /usr/local/bin/kubectl

rke_cluster_kube_config: /root/.kube/config


rancher_certmanager_crd_url: "https://github.com/jetstack/cert-manager/releases/download/v{{ helm_certmanager_version }}/cert-manager.crds.yaml"

### FQDN of rancher load balancer. create ingress rule for fqdn
rancher_hostname: rancher-lb.tcs.local

rancher_certmanager_enabled: true
rancher_generated_self_signed_certificates: true
rancher_lets_encrypt_generated_certificated: false
rancher_bring_your_own_certificates: false

