- name: Download kubectl binary
  get_url:
    url: "{{ kubectl_binary_download_url }}"
    dest: "{{ kubectl_binary_dest }}"
    mode: 0755
    force: yes
  changed_when: false

- name: Retrieve helm binary archive
  unarchive:
    src: "{{ helm_binary_download_url }}"
    dest: "./"
    remote_src: yes
  changed_when: false
  check_mode: no

- name: Move helm binary into place
  copy:
    src: "linux-amd64/helm"
    dest: "{{ helm_binary_dest }}"
    mode: 0755
    force: yes
  changed_when: false

