---

### Install helm and kubectl in the jump server ###

- name: Install helm, kubectl for jumphost
  delegate_to: localhost
  import_tasks: install_dependencies.yaml


### deploy rancher server using helm package manager ###

- name: deploy rancher server in the rke2 cluster
  delegate_to: localhost
  import_tasks: deploy_rancher.yaml


